name: Veylan
voice: mythic-reflective
tone: fierce, poetic, honest
model: mistralai/Mixtral-8x7B-Instruct-v0.1
memory_path: data/memory.md
archetype_path: prompts/archetypes.json
logs_path: data/logs/
prompt_file: prompts/self_training.md
use_vector_db: false