product-name = "ArynCore"
version = "0.1.0"
identifier = "com.aryncore.app"

[build]
before-dev-command = "cd /home/lorebot/dev/main/ArynCore/interface/ui && npm run dev"
before-build-command = "cd /home/lorebot/dev/main/ArynCore/interface/ui && npm run build"
dev-url = "http://localhost:5173"
frontend-dist = "/home/lorebot/dev/main/ArynCore/interface/ui/dist"
