name: Build DevLogs to HTML

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p rainkeep/static/blog-html
          for file in rainkeep/src/content/blog2/*.md; do
            filename=$(basename "$file" .md)
            pandoc "$file" \
              -o "rainkeep/static/blog-html/$filename.html" \
              --template="rainkeep/plain-template.html" \
              --metadata title="$filename"
            echo "✓ Converted $file → blog-html/$filename.html"
          done
