name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Tests
        working-directory: rust_projects/spotify_playlist_maker  # ✅ Correct path
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt  # ✅ Ensure Clippy and `cargo fmt` are installed

      - name: Run Clippy (Linting)
        working-directory: rust_projects/spotify_playlist_maker  # ✅ Correct path
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check Formatting
        working-directory: rust_projects/spotify_playlist_maker  # ✅ Correct path
        run: cargo fmt --check
